func main() {
    fmt.Println("=== Тестирование массива ===")
    arr := NewArray()
    arr.Append(1)
    arr.Append(2)
    arr.Append(3)
    arr.Add(1, 1.5)
    fmt.Printf("Массив: %s, Длина: %d\n", arr.String(), arr.Length())
    
    fmt.Println("\n=== Тестирование односвязного списка ===")
    sll := NewSinglyLinkedList()
    sll.AddToHead(1)
    sll.AddToTail(3)
    sll.AddAfter(1, 2)
    fmt.Printf("Односвязный список: %s, Размер: %d\n", sll.String(), sll.Size())
    
    fmt.Println("\n=== Тестирование двусвязного списка ===")
    dll := NewDoublyLinkedList()
    dll.AddToHead(1)
    dll.AddToTail(3)
    dll.AddBefore(3, 2)
    fmt.Printf("Двусвязный список вперед: %v\n", dll.ReadForward())
    fmt.Printf("Двусвязный список назад: %v\n", dll.ReadBackward())
    
    fmt.Println("\n=== Тестирование стека ===")
    stack := NewStack()
    stack.Push(1)
    stack.Push(2)
    stack.Push(3)
    fmt.Printf("Стек: %s\n", stack.String())
    stack.Pop()
    fmt.Printf("Стек после pop: %s\n", stack.String())
    
    fmt.Println("\n=== Тестирование очереди ===")
    queue := NewQueue()
    queue.Enqueue(1)
    queue.Enqueue(2)
    queue.Enqueue(3)
    fmt.Printf("Очередь: %s\n", queue.String())
    queue.Dequeue()
    fmt.Printf("Очередь после dequeue: %s\n", queue.String())
    
    fmt.Println("\n=== Тестирование полного бинарного дерева ===")
    tree := NewFullBinaryTree()
    tree.Add(1)
    tree.Add(2)
    tree.Add(3)
    tree.Add(4)
    tree.Add(5)
    fmt.Printf("Дерево InOrder: %v\n", tree.InOrder())
    fmt.Printf("Дерево LevelOrder: %v\n", tree.LevelOrder())
}
